---
namespace: "zt_yaml_essentials_for_ansible"
name: "automation"
version: "1.0.0"
readme: README.md
authors:
  - "mrudisill26 mrudisil@redhat.com"
description: "Starter collection for this project's custom Ansible automation."
license: []
repository: "https://github.com/rhpds/zt-yaml-essentials-for-ansible"
