---
type: showroom

default_width: 30
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  - name: ">_ terminal"
    path: /wetty
    port: 443
  - name: Placeholder
    url: /placeholder
