---
site:
  title: My Project
  url: https://github.com/rhpds/my-project
  start_page: modules::index.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/nookbag-bundle/releases/download/v0.0.3/ui-bundle.zip
    snapshot: true

output:
  dir: ./www
